version: "3"
services:
  epc-check:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4040:4000"
    command: sh -c "npm install && node server.js"
    restart: unless-stopped
